=== katherinefernandes/ProjectAOOSD/FinalProject/storage/activeData/dataStructure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="urn:Schema-Namespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:Schema-Namespace">

    <xsd:complexType name="ClientType">
    	<xsd:sequence>
    		<xsd:element name="ClientID" type="IDType"></xsd:element>
    		<xsd:element name="CompanyName" type="CompanyNameType"></xsd:element>
    		<xsd:element name="PhoneNumber" type="PhoneNumberType"></xsd:element>
    		<xsd:element name="Email" type="EmailType"></xsd:element>
    		<xsd:element name="RefrencePersonName" type="NameType"></xsd:element>
    		<xsd:element name="Address" type="AddressType"></xsd:element>
    		<xsd:element name="ActiveShipments" type="JourneyIDsType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:element name="Clients">
    <xsd:complexType>
    <xsd:sequence>
    		<xsd:element name="Client" type="ClientType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    </xsd:sequence>
    </xsd:complexType>
    </xsd:element>
    

    <xsd:simpleType name="PhoneNumberType">
    	<xsd:restriction base="xsd:int"></xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="EmailType">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="IDType">
    	<xsd:restriction base="xsd:long"></xsd:restriction>
    </xsd:simpleType>


    <xsd:complexType name="AddressType">
    	<xsd:sequence>
    		<xsd:element name="StreetName" type="xsd:string"></xsd:element>
    		<xsd:element name="HouseNumber" type="xsd:int"></xsd:element>
    		<xsd:element name="City" type="xsd:string"></xsd:element>
    		<xsd:element name="ZipCode" type="xsd:int"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="NameType">
    	<xsd:sequence>
    		<xsd:element name="FirstName" type="xsd:string"></xsd:element>
    		<xsd:element name="MiddleName" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    		<xsd:element name="LastName" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Containers" type="ContainersType"></xsd:element>
    
    <xsd:complexType name="ContainersType">
    	<xsd:sequence>
    		<xsd:element name="Container" type="ContainerType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ContainerType">
    	<xsd:sequence>
            <xsd:element name="ContainerID" type="IDType"></xsd:element>
            <xsd:element name="ClientID" type="IDType"></xsd:element>
    		<xsd:element name="JourneyID" type="IDType"></xsd:element>
    		<xsd:element name="StartPortID" type="IDType"></xsd:element>
    		<xsd:element name="DestionationPortID" type="IDType"></xsd:element>
    		<xsd:element name="CurrentPosition" type="PositionType"></xsd:element>
    		<xsd:element name="Cargo" type="CargoType"></xsd:element>
    		<xsd:element name="InternalState" type="InternalStateType">
    		</xsd:element>
    		<xsd:element name="Updated" type="xsd:dateTime"></xsd:element>
    		<xsd:element name="ArriveBy" type="xsd:dateTime"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="CompanyNameType">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="PortType">
    	<xsd:sequence>
    		<xsd:element name="PortID" type="IDType"></xsd:element>
    		<xsd:element name="Country" type="CountryType"></xsd:element>
    		<xsd:element name="PortName" type="PortNameType"></xsd:element>
    		<xsd:element name="Position" type="PositionType"></xsd:element>
    		<xsd:element name="StationedContainers" type="ContainerIDsType">
    		</xsd:element>
    		<xsd:element name="ArrivingContainers" type="ContainerIDsType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="CountryType">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="PortNameType">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="PositionType">
    	<xsd:sequence>
    		<xsd:element name="Latitude" type="xsd:float"></xsd:element>
    		<xsd:element name="Longitude" type="xsd:float"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="CargoType">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="InternalStateType">
    	<xsd:sequence>
    		<xsd:element name="Temperature" type="xsd:float"></xsd:element>
    		<xsd:element name="Atmosphere" type="xsd:float"></xsd:element>
    		<xsd:element name="Humidity" type="xsd:float"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Ports" type="PortsType"></xsd:element>
    
    <xsd:complexType name="PortsType">
    	<xsd:sequence>
    		<xsd:element name="Port" type="PortType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="History" type="HistoryType"></xsd:element>
    
    <xsd:complexType name="HistoryType">
    	<xsd:sequence>
    		<xsd:element name="DataPoint" type="DataPointType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="DataPointType">
    	<xsd:sequence>
    		<xsd:element name="TimeStamp" type="xsd:dateTime"></xsd:element>
    		<xsd:element name="ContainerID" type="IDType"></xsd:element>
    		<xsd:element name="JourneyID" type="IDType"></xsd:element>
    		<xsd:element name="ClientID" type="IDType"></xsd:element>
    		<xsd:element name="DestinationPortID" type="IDType"></xsd:element>
    		<xsd:element name="StartPortID" type="IDType"></xsd:element>
    		<xsd:element name="Cargo" type="CargoType"></xsd:element>
    		<xsd:element name="InternalState" type="InternalStateType">
    		</xsd:element>
    		<xsd:element name="Location" type="PositionType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ContainerIDsType">
    	<xsd:sequence>
    		<xsd:element name="ContainerID" type="IDType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="JourneyIDsType">
    	<xsd:sequence>
    		<xsd:element name="JourneyID" type="IDType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


</xsd:schema>

=== katherinefernandes/ProjectAOOSD/FinalProject/storage/activeData/containers.xml
<?xml version="1.0"?><Containers xmlns="urn:Schema-Namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:Schema-Namespace dataStructure.xsd "><Container ID="10849147913500"><ClientID>897841664500</ClientID><JourneyID>12708737599400</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>26.11</Latitude><Longitude>74.33</Longitude></CurrentPosition><Cargo>snacks</Cargo><InternalState><Temperature>36.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>78.0</Humidity></InternalState><Updated>2020-04-16T15:12:12</Updated><ArriveBy>2020-06-23T12:00</ArriveBy></Container><Container ID="12708682651400"><ClientID>0</ClientID><JourneyID>12915057106300</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:15:38</Updated><ArriveBy>2020-04-16T15:15:38</ArriveBy></Container><Container ID="12708736180700"><ClientID>0</ClientID><JourneyID>12819232224900</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:14:03</Updated><ArriveBy>2020-04-16T15:14:03</ArriveBy></Container><Container ID="12708736452900"><ClientID>0</ClientID><JourneyID>12792237656500</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:13:36</Updated><ArriveBy>2020-04-16T15:13:36</ArriveBy></Container><Container ID="12708736625200"><ClientID>0</ClientID><JourneyID>12723422024300</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:12:27</Updated><ArriveBy>2020-04-16T15:12:27</ArriveBy></Container><Container ID="12708736872800"><ClientID>0</ClientID><JourneyID>0</JourneyID><StartPortID>12708675509600</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>55.7</Latitude><Longitude>12.59</Longitude></CurrentPosition><Cargo>none</Cargo><InternalState><Temperature>35.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>75.0</Humidity></InternalState><Updated>2020-04-16T15:12:12</Updated><ArriveBy>2020-04-16T15:12:12</ArriveBy></Container><Container ID="12708737034600"><ClientID>0</ClientID><JourneyID>0</JourneyID><StartPortID>12708675509600</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>55.7</Latitude><Longitude>12.59</Longitude></CurrentPosition><Cargo>none</Cargo><InternalState><Temperature>35.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>75.0</Humidity></InternalState><Updated>2020-04-16T15:12:12</Updated><ArriveBy>2020-04-16T15:12:12</ArriveBy></Container><Container ID="12985485931900"><ClientID>0</ClientID><JourneyID>12985866966400</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:16:49</Updated><ArriveBy>2020-04-16T15:16:49</ArriveBy></Container><Container ID="13635886882300"><ClientID>0</ClientID><JourneyID>13636014112800</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:27:39</Updated><ArriveBy>2020-04-16T15:27:39</ArriveBy></Container><Container ID="13678821291400"><ClientID>0</ClientID><JourneyID>13679009012900</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:28:22</Updated><ArriveBy>2020-04-16T15:28:22</ArriveBy></Container><Container ID="13778387788600"><ClientID>0</ClientID><JourneyID>13778607452800</JourneyID><StartPortID>12708669367300</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>25.11</Latitude><Longitude>62.33</Longitude></CurrentPosition><Cargo>Mangoes</Cargo><InternalState><Temperature>10.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>90.0</Humidity></InternalState><Updated>2020-04-16T15:30:02</Updated><ArriveBy>2020-04-16T15:30:02</ArriveBy></Container><Container ID="73013416799200"><ClientID>0</ClientID><JourneyID>0</JourneyID><StartPortID>12708675509600</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>55.7</Latitude><Longitude>12.59</Longitude></CurrentPosition><Cargo>none</Cargo><InternalState><Temperature>35.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>75.0</Humidity></InternalState><Updated>2020-04-16T15:12:12</Updated><ArriveBy>2020-04-16T15:12:12</ArriveBy></Container><Container ID="521664805370600"><ClientID>0</ClientID><JourneyID>0</JourneyID><StartPortID>12708675509600</StartPortID><DestinationPortID>12708675509600</DestinationPortID><CurrentPosition><Latitude>55.7</Latitude><Longitude>12.59</Longitude></CurrentPosition><Cargo>none</Cargo><InternalState><Temperature>35.0</Temperature><Atmosphere>1.0</Atmosphere><Humidity>75.0</Humidity></InternalState><Updated>2020-04-16T15:12:12</Updated><ArriveBy>2020-04-16T15:12:12</ArriveBy></Container></Containers>

=== katherinefernandes/ProjectAOOSD/FinalProject/storage/ports.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Ports xmlns:tns="dataStructure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="dataStructure dataStructure.xsd ">
  <tns:Port>
    <tns:PortID>0</tns:PortID>
    <tns:Country>tns:Country</tns:Country>
    <tns:PortName>tns:PortName</tns:PortName>
    <tns:Position>
      <tns:Latitude>0.0</tns:Latitude>
      <tns:Longitude>0.0</tns:Longitude>
    </tns:Position>
    <tns:StationedContainers/>
    <tns:ArrivingContainers/>
  </tns:Port>
</tns:Ports>

=== katherinefernandes/ProjectAOOSD/FinalProject/storage/clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Clients xmlns:tns="dataStructure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="dataStructure dataStructure.xsd ">
  <tns:Client>
    <tns:ClientID>0</tns:ClientID>
    <tns:CompanyName>tns:CompanyName</tns:CompanyName>
    <tns:PhoneNumber>0</tns:PhoneNumber>
    <tns:Email>tns:Email</tns:Email>
    <tns:RefrencePersonName>
      <tns:FirstName>tns:FirstName</tns:FirstName>
      <tns:LastName>tns:LastName</tns:LastName>
    </tns:RefrencePersonName>
    <tns:Address>
      <tns:StreetName>tns:StreetName</tns:StreetName>
      <tns:HouseNumber>0</tns:HouseNumber>
      <tns:City>tns:City</tns:City>
      <tns:ZipCode>0</tns:ZipCode>
    </tns:Address>
    <tns:ActiveShipments/>
  </tns:Client>
</tns:Clients>

=== katherinefernandes/ProjectAOOSD/FinalProject/storage/emptyData/history.xml
<?xml version="1.0" encoding="UTF-8"?>
<History xmlns="urn:Schema-Namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:Schema-Namespace dataStructure.xsd ">
  <DataPoint>
    <TimeStamp>2001-12-31T12:00:00</TimeStamp>
    <ContainerID>0</ContainerID>
    <JourneyID>0</JourneyID>
    <ClientID>0</ClientID>
    <DestinationPortID>0</DestinationPortID>
    <StartPortID>0</StartPortID>
    <Cargo>Cargo</Cargo>
    <InternalState>
      <Temperature>0.0</Temperature>
      <Atmosphere>0.0</Atmosphere>
      <Humidity>0.0</Humidity>
    </InternalState>
    <Location>
      <Latitude>0.0</Latitude>
      <Longitude>0.0</Longitude>
    </Location>
  </DataPoint>
</History>

=== katherinefernandes/ProjectAOOSD/FinalProject/storage/history.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:History xmlns:tns="dataStructure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="dataStructure dataStructure.xsd ">
  <tns:DataPoint>
    <tns:TimeStamp>2001-12-31T12:00:00</tns:TimeStamp>
    <tns:ContainerID>0</tns:ContainerID>
    <tns:JourneyID>0</tns:JourneyID>
    <tns:ClientID>0</tns:ClientID>
    <tns:DestinationPortID>0</tns:DestinationPortID>
    <tns:StartPortID>0</tns:StartPortID>
    <tns:Cargo>tns:Cargo</tns:Cargo>
    <tns:InternalState>
      <tns:Temperature>0.0</tns:Temperature>
      <tns:Atmosphere>0.0</tns:Atmosphere>
      <tns:Humidity>0.0</tns:Humidity>
    </tns:InternalState>
    <tns:Location>
      <tns:Latitude>0.0</tns:Latitude>
      <tns:Longitude>0.0</tns:Longitude>
    </tns:Location>
  </tns:DataPoint>
</tns:History>
